FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

ENV DATABASE_URL=${DATABASE_URL}

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate

RUN bun run build || (echo "Build failed. Showing logs..." && cat /usr/src/app/apps/web/.next/trace && exit 1)

EXPOSE 3000

CMD ["bun", "run", "start:frontend"]
